[[fallback-headers]]
= `FallbackHeaders` 网关过滤器工厂（`GatewayFilter` Factory）

`FallbackHeaders` 工厂允许你在请求转发到外部应用程序中的 `fallbackUri` 时，将 Spring Cloud CircuitBreaker 执行异常的详细信息添加到请求头中。例如以下场景：

.application.yml
[source,yaml]
----
spring:
  cloud:
    gateway:
      routes:
      - id: ingredients
        uri: lb://ingredients
        predicates:
        - Path=/ingredients/**
        filters:
        - name: CircuitBreaker
          args:
            name: fetchIngredients
            fallbackUri: forward:/fallback
      - id: ingredients-fallback
        uri: http://localhost:9994
        predicates:
        - Path=/fallback
        filters:
        - name: FallbackHeaders
          args:
            executionExceptionTypeHeaderName: Test-Header
----

在此示例中，当执行断路器过程中发生执行异常时，请求会被转发至运行在 `localhost:9994` 上的应用程序的 `fallback` 端点或处理器。  
`FallbackHeaders` 过滤器会将包含异常类型、异常消息以及（如果可用）根本原因异常类型和消息的头部信息添加到该请求中。

你可以通过设置以下参数来覆盖这些头部字段的名称（括号内为默认值）：

* `executionExceptionTypeHeaderName` （默认值：`"Execution-Exception-Type"`）
* `executionExceptionMessageHeaderName` （默认值：`"Execution-Exception-Message"`）
* `rootCauseExceptionTypeHeaderName` （默认值：`"Root-Cause-Exception-Type"`）
* `rootCauseExceptionMessageHeaderName` （默认值：`"Root-Cause-Exception-Message"`）

有关断路器和网关的更多信息，请参见 xref:spring-cloud-gateway-server-webflux/gatewayfilter-factories/circuitbreaker-filter-factory.adoc[Spring Cloud CircuitBreaker 工厂章节]。