[[retry-gatewayfilter-factory]]
= `Retry` `GatewayFilter` 工厂

`Retry` `GatewayFilter` 工厂支持以下参数：

* `retries`：应尝试重试的次数。
* `statuses`：应进行重试的HTTP状态码，使用 `org.springframework.http.HttpStatus` 表示。
* `methods`：应进行重试的HTTP方法，使用 `org.springframework.http.HttpMethod` 表示。
* `series`：应进行重试的状态码系列，使用 `org.springframework.http.HttpStatus.Series` 表示。
* `exceptions`：应触发重试的异常列表。
* `backoff`：配置的指数退避策略（exponential backoff）用于重试。  
  重试将在间隔 `firstBackoff * (factor ^ n)` 后执行，其中 `n` 是当前重试的次数（从0开始）。  
  如果配置了 `maxBackoff`，则最大退避时间不会超过 `maxBackoff`。  
  如果 `basedOnPreviousValue` 为 `true`，则退避时间按 `prevBackoff * factor` 计算。
* `jitter`：配置的随机抖动（random jitter）用于重试。  
  实际退避时间将在 `[backoff - backoff*randomFactor, backoff + backoff*randomFactor]` 范围内随机生成。
* `timeout`：配置的重试超时时间。

如果启用了 `Retry` 过滤器，则默认配置如下：

* `retries`：3次
* `series`：5XX 系列状态码
* `methods`：GET 方法
* `exceptions`：`IOException` 和 `TimeoutException`
* `backoff`：未启用
* `jitter`：未启用
* `timeout`：无限制

以下示例配置了一个 `Retry` `GatewayFilter`：

.application.yml
[source,yaml]
----
spring:
  cloud:
    gateway:
      routes:
      - id: retry_test
        uri: http://localhost:8080/flakey
        predicates:
        - Host=*.retry.com
        filters:
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY
            methods: GET,POST
            backoff:
              firstBackoff: 10ms
              maxBackoff: 50ms
              factor: 2
              basedOnPreviousValue: false
            jitter:
              randomFactor: 0.5
            timeout: 100ms
----

NOTE: 当将重试过滤器与以 `forward:` 开头的URL一起使用时，目标端点应谨慎编写，确保在发生错误时不会执行可能导致响应发送给客户端并提交的操作。  
例如，如果目标端点是一个注解控制器，那么目标控制器方法不应返回带有错误状态码的 `ResponseEntity`。  
相反，它应抛出一个 `Exception` 或发出错误信号（例如通过返回 `Mono.error(ex)`），以便重试过滤器能够捕获并根据配置进行重试。

NOTE: 使用重试过滤器时，它会重试其之后的所有过滤器。请确保在多次执行时，位于重试过滤器之后的过滤器行为符合预期。

WARNING: 当对带有请求体的任何HTTP方法使用重试过滤器时，请求体会被缓存，这可能导致网关内存受限。  
请求体被缓存在由 `ServerWebExchangeUtils.CACHED_REQUEST_BODY_ATTR` 定义的请求属性中，对象类型为 `org.springframework.core.io.buffer.DataBuffer`。

可以使用简化的“快捷方式”表示法，仅指定单个 `status` 和 `method`。

以下两个示例是等效的：

.application.yml
[source,yaml]
----
spring:
  cloud:
    gateway:
      routes:
      - id: retry_route
        uri: https://example.org
        filters:
        - name: Retry
          args:
            retries: 3
            statuses: INTERNAL_SERVER_ERROR
            methods: GET
            backoff:
              firstBackoff: 10ms
              maxBackoff: 50ms
              factor: 2
              basedOnPreviousValue: false
            jitter:
              randomFactor: 0.5
            timeout: 100ms

      - id: retryshortcut_route
        uri: https://example.org
        filters:
        - Retry=3,INTERNAL_SERVER_ERROR,GET,10ms,50ms,2,false,0.5,100ms
----