= Spring Session - Spring Boot
Rob Winch, Vedran Pavić
:stylesdir: ../
:highlightjsdir: ../js/highlight
:docinfodir: guides

本指南介绍如何在使用 Spring Boot 时，通过 Spring Session 透明地利用 Redis 来支持 Web 应用程序的 `HttpSession`。

NOTE: 完整的示例代码可在 <<boot-sample, boot 示例应用程序>> 中找到。

[#index-link]
link:../index.html[索引]

== 更新依赖项

在使用 Spring Session 配合 Redis 之前，必须确保已添加正确的依赖项。我们假设你正在开发一个正常的 Spring Boot Web 应用程序。

====
.pom.xml
[source,xml,role="primary"]
[subs="verbatim,attributes"]
----
<dependencies>
	<!-- ... -->

	<dependency>
		<groupId>org.springframework.session</groupId>
		<artifactId>spring-session-data-redis</artifactId>
	</dependency>
</dependencies>
----

.build.gradle
[source,groovy,role="secondary"]
----
implementation("org.springframework.session:spring-session-data-redis")
----
====

Spring Boot 为 Spring Session 模块提供了依赖管理，因此无需显式声明依赖版本。

[[boot-spring-configuration]]
== Spring Boot 配置

添加所需依赖后，我们可以创建 Spring Boot 配置。得益于一流的自动配置支持，只需添加依赖，Spring Boot 就会为我们自动配置由 Redis 支持的 Spring Session。

底层机制上，Spring Boot 实际上应用了与手动添加 `@EnableRedisHttpSession` 注解等效的配置。这将创建一个名为 `springSessionRepositoryFilter` 的 Spring Bean，该 Bean 实现了 `Filter` 接口。此过滤器负责将默认的 `HttpSession` 实现替换为由 Spring Session 支持的实现。

还可以通过 `application.properties` 进行进一步自定义，如下所示：

====
.src/main/resources/application.properties
----
server.servlet.session.timeout= # 会话超时时间。若未指定时间单位，默认单位为秒。
spring.session.redis.flush-mode=on_save # 会话刷新模式。
spring.session.redis.namespace=spring:session # 存储会话所使用的键命名空间。
----
====

更多详细信息，请参阅 Spring Boot 文档中关于 {docs-url}/spring-boot/docs/{spring-boot-version}/reference/htmlsingle/#boot-features-session[Spring Session] 的部分。

[[boot-redis-configuration]]
== 配置 Redis 连接

Spring Boot 会自动创建一个 `RedisConnectionFactory`，连接到运行在本地主机（localhost）6379 端口上的 Redis 服务器（默认端口）。在生产环境中，你需要更新配置以指向实际的 Redis 服务器。例如，可以在 `application.properties` 中包含以下内容：

====
.src/main/resources/application.properties
----
spring.data.redis.host=localhost # Redis 服务器主机地址。
spring.data.redis.password= # Redis 服务器登录密码。
spring.data.redis.port=6379 # Redis 服务器端口。
----
====

更多详细信息，请参阅 Spring Boot 文档中关于 {docs-url}/spring-boot/docs/{spring-boot-version}/reference/htmlsingle/#boot-features-connecting-to-redis[连接 Redis] 的部分。

[[boot-servlet-configuration]]
== Servlet 容器初始化

我们的 <<boot-spring-configuration,Spring Boot 配置>> 创建了一个名为 `springSessionRepositoryFilter` 的 Spring Bean，它实现了 `Filter` 接口。这个 `springSessionRepositoryFilter` Bean 负责将标准的 `HttpSession` 替换为由 Spring Session 支持的自定义实现。

为了让该过滤器生效，Spring 必须加载我们的配置类（`Config` 类）。最后，还需确保 Servlet 容器（如 Tomcat）在每个请求中都使用这个 `springSessionRepositoryFilter`。幸运的是，这些步骤均由 Spring Boot 自动完成。

[[boot-sample]]
== Boot 示例应用程序

该 Boot 示例应用程序演示了如何在使用 Spring Boot 时，通过 Spring Session 透明地利用 Redis 来支持 Web 应用程序的 `HttpSession`。

[[boot-running]]
=== 运行 Boot 示例应用程序

你可以通过获取 {download-url}[源码] 并执行以下命令来运行示例：

====
----
$ ./gradlew :spring-session-sample-boot-redis:bootRun
----
====

NOTE: 要使示例正常运行，你必须在本地主机上 https://redis.io/download[安装 Redis 2.8 或更高版本]，并使用默认端口（6379）启动。或者，你可以修改 `RedisConnectionFactory` 以指向其他 Redis 服务器。另一种选择是使用 https://www.docker.com/[Docker] 在本地运行 Redis。详细的安装说明请参考 https://hub.docker.com/_/redis/[Docker Redis 仓库]。

完成后，你现在可以通过 http://localhost:8080/ 访问该应用程序。

[[boot-explore]]
=== 探索 `security` 示例应用程序

现在可以尝试使用该应用。输入以下凭据进行登录：

* *用户名* _user_
* *密码* _password_

点击 *登录* 按钮后，你应该会看到一条消息，表明你已使用之前输入的用户身份成功登录。该用户的信息被存储在 Redis 中，而不是 Tomcat 的 `HttpSession` 实现中。

[[boot-how]]
=== 原理是什么？

我们没有使用 Tomcat 的 `HttpSession`，而是将数据持久化到 Redis 中。Spring Session 使用基于 Redis 的实现替换了 `HttpSession`。当 Spring Security 的 `SecurityContextPersistenceFilter` 将 `SecurityContext` 保存到 `HttpSession` 时，实际上该上下文被持久化到了 Redis 中。

每当创建一个新的 `HttpSession` 时，Spring Session 会在浏览器中生成一个名为 `SESSION` 的 Cookie，其中包含会话的 ID。你可以使用 https://developers.google.com/web/tools/chrome-devtools/manage-data/cookies[Chrome] 或 https://developer.mozilla.org/en-US/docs/Tools/Storage_Inspector[Firefox] 的开发者工具查看这些 Cookie。

你可以使用 `redis-cli` 删除会话。例如，在基于 Linux 的系统中，可以输入以下命令：

====
----
	$ redis-cli keys '*' | xargs redis-cli del
----
====

TIP: Redis 官方文档提供了 https://redis.io/topics/quickstart[安装 redis-cli] 的说明。

另外，也可以删除特定的键。在终端中输入以下命令，并将 `7e8383a4-082c-4ffe-a4bc-c40fd3363c5e` 替换为你当前 `SESSION` Cookie 的值：

====
----
	$ redis-cli del spring:session:sessions:7e8383a4-082c-4ffe-a4bc-c40fd3363c5e
----
====

此时再访问 http://localhost:8080/，你会发现已经不再处于认证状态。