= Spring Session - HttpSession（快速入门）
Rob Winch
:version-snapshot: true
:stylesdir: ../
:highlightjsdir: ../js/highlight
:docinfodir: guides

本指南介绍了如何使用 Spring Session 通过 Java 配置透明地利用 Redis 来支持 Web 应用程序的 `HttpSession`。

NOTE: 您可以在 <<httpsession-sample, httpsession 示例应用>> 中找到完整的指南。

[#index-link]
link:../index.html[首页]

== 更新依赖项
在使用 Spring Session 之前，您必须更新项目的依赖项。  
如果您使用的是 Maven，则需要添加以下依赖：

====
.pom.xml
[source,xml]
[subs="verbatim,attributes"]
----
<dependencies>
	<!-- ... -->

	<dependency>
		<groupId>org.springframework.session</groupId>
		<artifactId>spring-session-data-redis</artifactId>
		<version>{spring-session-version}</version>
		<type>pom</type>
	</dependency>
	<dependency>
		<groupId>io.lettuce</groupId>
		<artifactId>lettuce-core</artifactId>
		<version>{lettuce-core-version}</version>
	</dependency>
	<dependency>
		<groupId>org.springframework</groupId>
		<artifactId>spring-web</artifactId>
		<version>{spring-core-version}</version>
	</dependency>
</dependencies>
----
====

ifeval::["{version-snapshot}" == "true"]
由于我们使用的是 SNAPSHOT 版本，因此需要添加 Spring 快照仓库。请确保您的 pom.xml 包含以下内容：

====
.pom.xml
[source,xml]
----
<repositories>

	<!-- ... -->

	<repository>
		<id>spring-snapshot</id>
		<url>https://repo.spring.io/libs-snapshot</url>
	</repository>
</repositories>
----
====
endif::[]

ifeval::["{version-milestone}" == "true"]
由于我们使用的是里程碑版本，因此需要添加 Spring 里程碑仓库。请确保您的 pom.xml 包含以下内容：

====
.pom.xml
[source,xml]
----
<repository>
	<id>spring-milestone</id>
	<url>https://repo.spring.io/libs-milestone</url>
</repository>
----
====
endif::[]

// tag::config[]

[[httpsession-spring-configuration]]
== Spring Java 配置

添加所需依赖后，我们可以创建 Spring 配置。该配置负责创建一个 Servlet 过滤器（Filter），用由 Spring Session 支持的实现来替换默认的 `HttpSession` 实现。为此，请添加如下 Spring 配置：

====
[source,java]
----
include::{samples-dir}spring-session-sample-javaconfig-redis/src/main/java/sample/Config.java[tags=class]
----

<1> `@EnableRedisHttpSession` 注解会创建一个名为 `springSessionRepositoryFilter` 的 Spring Bean，它实现了 `Filter` 接口。该过滤器负责将 `HttpSession` 的实现替换为由 Spring Session 支持的自定义实现。在此示例中，Spring Session 由 Redis 提供支持。  
<2> 我们创建了一个 `RedisConnectionFactory`，用于连接 Spring Session 到 Redis 服务器。此处配置为连接本地主机上的默认端口（6379）。有关 Spring Data Redis 配置的更多信息，请参见 {docs-url}/spring-data/data-redis/docs/{spring-data-redis-version}/reference/html/[参考文档]。
====

== Java Servlet 容器初始化

我们的 <<httpsession-spring-configuration,Spring 配置>> 创建了一个名为 `springSessionRepositoryFilter` 的 Spring Bean，该 Bean 实现了 `Filter` 接口。`springSessionRepositoryFilter` 负责将标准的 `HttpSession` 替换为由 Spring Session 支持的自定义实现。

为了让这个过滤器生效，Spring 必须加载我们的 `Config` 类。此外，我们必须确保 Servlet 容器（例如 Tomcat）在每个请求中都使用 `springSessionRepositoryFilter`。幸运的是，Spring Session 提供了一个工具类 `AbstractHttpSessionApplicationInitializer`，可以轻松完成这两个步骤。以下是一个示例：

====
.src/main/java/sample/Initializer.java
[source,java]
----
include::{samples-dir}spring-session-sample-javaconfig-redis/src/main/java/sample/Initializer.java[tags=class]
----

NOTE: 类名（如 `Initializer`）不重要，关键是我们继承了 `AbstractHttpSessionApplicationInitializer`。

<1> 第一步是继承 `AbstractHttpSessionApplicationInitializer`。这样可确保名为 `springSessionRepositoryFilter` 的 Spring Bean 被注册到 Servlet 容器，并应用于每个请求。  
<2> `AbstractHttpSessionApplicationInitializer` 还提供了一种机制，确保 Spring 能够加载我们的 `Config` 配置类。
====
// end::config[]

[[httpsession-sample]]
== httpsession 示例应用程序

=== 运行 `httpsession` 示例应用程序

您可以通过获取 {download-url}[源代码] 并执行以下命令来运行此示例：

====
----
$ ./gradlew :spring-session-sample-javaconfig-redis:tomcatRun
----
====

NOTE: 要使示例正常工作，您必须在本地主机上 https://redis.io/download[安装 Redis 2.8 或更高版本]，并使用默认端口（6379）运行。或者，您可以修改 `RedisConnectionFactory` 以指向其他 Redis 服务器。另一种选择是使用 https://www.docker.com/[Docker] 在本地运行 Redis。详细说明请参阅 https://hub.docker.com/_/redis/[Docker Redis 仓库]。

现在，您应该可以通过 http://localhost:8080/ 访问该应用程序。

=== 探索 `httpsession` 示例应用程序

现在您可以尝试使用该应用。填写以下表单信息：

* *属性名称:* _username_  
* *属性值:* _rob_

然后点击 *Set Attribute* 按钮。您应该能在下方表格中看到显示的值。

=== 它是如何工作的？

我们在如下所示的 `SessionServlet` 中与标准的 `HttpSession` 进行交互：

====
.src/main/java/sample/SessionServlet.java
[source,java]
----
include::{samples-dir}spring-session-sample-javaconfig-redis/src/main/java/sample/SessionServlet.java[tags=class]
----
====

实际上，我们并未使用 Tomcat 自带的 `HttpSession`，而是将数据持久化存储在 Redis 中。Spring Session 会在您的浏览器中创建一个名为 `SESSION` 的 Cookie，其中包含会话的 ID。您可以通过 https://developers.google.com/web/tools/chrome-devtools/manage-data/cookies[Chrome] 或 https://developer.mozilla.org/en-US/docs/Tools/Storage_Inspector[Firefox] 的开发者工具查看这些 Cookie。

您也可以使用 `redis-cli` 删除会话。例如，在基于 Linux 的系统上，可以输入以下命令：

====
----
	$ redis-cli keys '*' | xargs redis-cli del
----
====

TIP: Redis 官方文档提供了关于 https://redis.io/topics/quickstart[安装 redis-cli] 的说明。

或者，您也可以删除特定的键。在终端中输入以下命令，并将 `7e8383a4-082c-4ffe-a4bc-c40fd3363c5e` 替换为您自己的 SESSION Cookie 值：

====
----
	$ redis-cli del spring:session:sessions:7e8383a4-082c-4ffe-a4bc-c40fd3363c5e
----
====

现在再次访问 http://localhost:8080/，您会发现之前添加的属性已不再显示。