= Spring Session - HttpSession（快速入门）
Rob Winch
:stylesdir: ../
:highlightjsdir: ../js/highlight
:docinfodir: guides

本指南介绍如何使用 Spring Session，通过基于 XML 的配置，透明地利用 Redis 来支持 Web 应用程序的 `HttpSession`。

NOTE: 你可以在 <<httpsession-xml-sample, httpsession-xml 示例应用>> 中找到完整的指南。

[#index-link]
link:../index.html[索引]

== 更新依赖项
在使用 Spring Session 之前，必须先更新项目的依赖。  
如果你使用的是 Maven，请添加以下依赖：

====
.pom.xml
[source,xml]
[subs="verbatim,attributes"]
----
<dependencies>
	<!-- ... -->

	<dependency>
		<groupId>org.springframework.session</groupId>
		<artifactId>spring-session-data-redis</artifactId>
		<version>{spring-session-version}</version>
		<type>pom</type>
	</dependency>
	<dependency>
		<groupId>io.lettuce</groupId>
		<artifactId>lettuce-core</artifactId>
		<version>{lettuce-core-version}</version>
	</dependency>
	<dependency>
		<groupId>org.springframework</groupId>
		<artifactId>spring-web</artifactId>
		<version>{spring-core-version}</version>
	</dependency>
</dependencies>
----
====

ifeval::["{version-snapshot}" == "true"]
由于我们使用的是 SNAPSHOT 版本，需要添加 Spring 快照仓库。请确保你的 pom.xml 包含以下内容：

====
.pom.xml
[source,xml]
----
<repositories>

	<!-- ... -->

	<repository>
		<id>spring-snapshot</id>
		<url>https://repo.spring.io/libs-snapshot</url>
	</repository>
</repositories>
----
====
endif::[]

ifeval::["{version-milestone}" == "true"]
由于我们使用的是里程碑版本，需要添加 Spring 里程碑仓库。请确保你的 pom.xml 包含以下内容：

====
.pom.xml
[source,xml]
----
<repository>
	<id>spring-milestone</id>
	<url>https://repo.spring.io/libs-milestone</url>
</repository>
----
====
endif::[]

// tag::config[]

[[httpsession-xml-spring-configuration]]
== Spring XML 配置

添加所需依赖后，我们可以创建 Spring 配置。该配置的作用是创建一个 Servlet 过滤器（Filter），将默认的 `HttpSession` 实现替换为由 Spring Session 支持的实现。为此，请添加如下 Spring 配置：

====
.src/main/webapp/WEB-INF/spring/session.xml
[source,xml,indent=0]
----
include::{samples-dir}spring-session-sample-xml-redis/src/main/webapp/WEB-INF/spring/session.xml[tags=beans]
----

<1> 我们结合使用 `<context:annotation-config/>` 和 `RedisHttpSessionConfiguration`，因为 Spring Session 目前尚未提供 XML 命名空间支持（参见 https://github.com/spring-projects/spring-session/issues/104[gh-104]）。这会创建一个名为 `springSessionRepositoryFilter` 且实现 `Filter` 接口的 Spring Bean。该过滤器负责将 `HttpSession` 的实现替换为由 Spring Session 支持的自定义实现。在此示例中，Spring Session 使用 Redis 作为后端存储。
<2> 我们创建了一个 `RedisConnectionFactory`，用于连接 Spring Session 与 Redis 服务器。配置中默认连接到本地主机（localhost）的 6379 端口。有关 Spring Data Redis 的更多配置信息，请参阅 {docs-url}/spring/docs/{spring-core-version}/spring-framework-reference/data-access.html#redis[参考文档]。
====

== XML Servlet 容器初始化

我们的 <<httpsession-xml-spring-configuration,Spring 配置>> 创建了一个名为 `springSessionRepositoryFilter` 的 Spring Bean，它实现了 `Filter` 接口。这个 Bean 负责将标准的 `HttpSession` 替换为由 Spring Session 支持的实现。

为了让该过滤器生效，我们需要指示 Spring 加载 `session.xml` 配置文件。可通过以下配置实现：

====
.src/main/webapp/WEB-INF/web.xml
[source,xml,indent=0]
----
include::{samples-dir}spring-session-sample-xml-redis/src/main/webapp/WEB-INF/web.xml[tags=context-param]
include::{samples-dir}spring-session-sample-xml-redis/src/main/webapp/WEB-INF/web.xml[tags=listeners]
----
====

{docs-url}/spring/docs/{spring-core-version}/spring-framework-reference/core.html#context-create[`ContextLoaderListener`] 会读取 `contextConfigLocation` 参数，并加载我们的 `session.xml` 配置。

最后，我们需要确保 Servlet 容器（如 Tomcat）对每个请求都使用 `springSessionRepositoryFilter`。以下代码片段完成了这一步骤：

====
.src/main/webapp/WEB-INF/web.xml
[source,xml,indent=0]
----
include::{samples-dir}spring-session-sample-xml-redis/src/main/webapp/WEB-INF/web.xml[tags=springSessionRepositoryFilter]
----
====

{docs-url}/spring-framework/docs/{spring-core-version}/javadoc-api/org/springframework/web/filter/DelegatingFilterProxy.html[`DelegatingFilterProxy`] 会查找名为 `springSessionRepositoryFilter` 的 Bean 并将其转换为 `Filter` 类型。每当有请求进入时，`DelegatingFilterProxy` 就会调用 `springSessionRepositoryFilter` 来处理。

// end::config[]

[[httpsession-xml-sample]]
== `httpsession-xml` 示例应用程序

本节介绍如何运行和使用 `httpsession-xml` 示例应用。

=== 运行 `httpsession-xml` 示例应用

你可以通过获取 {download-url}[源码] 并执行以下命令来运行示例：

NOTE: 要使示例正常运行，必须在本地主机上 https://redis.io/download[安装 Redis 2.8 或更高版本]，并使用默认端口（6379）启动。或者，你可以修改 `RedisConnectionFactory` 指向其他 Redis 服务器。另一种选择是使用 https://www.docker.com/[Docker] 在本地运行 Redis。详细说明请参见 https://hub.docker.com/_/redis/[Docker Redis 仓库]。

====
----
$ ./gradlew :spring-session-sample-xml-redis:tomcatRun
----
====

现在你应该可以通过 http://localhost:8080/ 访问该应用。

=== 探索 `httpsession-xml` 示例应用

现在可以尝试使用该应用。在表单中填写以下信息：

* *属性名称:* _username_
* *属性值:* _rob_

然后点击 *Set Attribute* 按钮。你应该能在下方表格中看到显示的值。

=== 它是如何工作的？

我们在如下所示的 `SessionServlet` 中与标准的 `HttpSession` 进行交互：

====
.src/main/java/sample/SessionServlet.java
[source,java]
----
include::{samples-dir}spring-session-sample-xml-redis/src/main/java/sample/SessionServlet.java[tags=class]
----
====

实际上，我们并未使用 Tomcat 自带的 `HttpSession`，而是将数据持久化到了 Redis 中。Spring Session 会在浏览器中创建一个名为 `SESSION` 的 Cookie，其中包含当前会话的 ID。你可以通过 https://developers.google.com/web/tools/chrome-devtools/manage-data/cookies[Chrome] 或 https://developer.mozilla.org/en-US/docs/Tools/Storage_Inspector[Firefox] 的开发者工具查看这些 Cookie。

你可以使用 `redis-cli` 删除会话。例如，在基于 Linux 的系统中，输入以下命令：

====
----
	$ redis-cli keys '*' | xargs redis-cli del
----
====

TIP: Redis 官方文档提供了关于 https://redis.io/topics/quickstart[安装 redis-cli] 的说明。

或者，你也可以手动删除特定的键。只需在终端中输入以下命令，并将 `7e8383a4-082c-4ffe-a4bc-c40fd3363c5e` 替换为你自己的 SESSION Cookie 值：

====
----
	$ redis-cli del spring:session:sessions:7e8383a4-082c-4ffe-a4bc-c40fd3363c5e
----
====

此时再次访问 http://localhost:8080/，你会发现之前设置的属性已不再显示。