[[oauth2client]]
= OAuth 2.0 客户端
:page-section-summary-toc: 1

OAuth 2.0 客户端功能提供了对 https://tools.ietf.org/html/rfc6749#section-1.1[OAuth 2.0 授权框架] 中定义的客户端角色的支持。

从高层来看，可用的核心功能包括：

.授权许可支持
* https://tools.ietf.org/html/rfc6749#section-1.3.1[授权码（Authorization Code）]
* https://tools.ietf.org/html/rfc6749#section-6[刷新令牌（Refresh Token）]
* https://tools.ietf.org/html/rfc6749#section-1.3.4[客户端凭据（Client Credentials）]
* https://tools.ietf.org/html/rfc6749#section-1.3.3[资源所有者密码凭据（Resource Owner Password Credentials）]
* https://datatracker.ietf.org/doc/html/rfc7523#section-2.1[JWT Bearer]
* https://datatracker.ietf.org/doc/html/rfc8693#section-2.1[令牌交换（Token Exchange）]

.客户端认证支持
* https://datatracker.ietf.org/doc/html/rfc7523#section-2.2[JWT Bearer]

.HTTP 客户端支持
* xref:servlet/oauth2/client/authorized-clients.adoc#oauth2Client-webclient-servlet[`WebClient` 在 Servlet 环境中的集成]（用于请求受保护资源）

`HttpSecurity.oauth2Client()` DSL 提供了多种配置选项，用于自定义 OAuth 2.0 客户端所使用的核心组件。此外，`HttpSecurity.oauth2Client().authorizationCodeGrant()` 允许对授权码授权流程进行定制。

以下代码展示了 `HttpSecurity.oauth2Client()` DSL 提供的完整配置选项：

.OAuth2 客户端配置选项
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebSecurity
public class OAuth2ClientSecurityConfig {

	@Bean
	public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
		http
			.oauth2Client(oauth2 -> oauth2
				.clientRegistrationRepository(this.clientRegistrationRepository())
				.authorizedClientRepository(this.authorizedClientRepository())
				.authorizedClientService(this.authorizedClientService())
				.authorizationCodeGrant(codeGrant -> codeGrant
					.authorizationRequestRepository(this.authorizationRequestRepository())
					.authorizationRequestResolver(this.authorizationRequestResolver())
					.accessTokenResponseClient(this.accessTokenResponseClient())
				)
			);
		return http.build();
	}
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Configuration
@EnableWebSecurity
class OAuth2ClientSecurityConfig {

    @Bean
    open fun filterChain(http: HttpSecurity): SecurityFilterChain {
        http {
            oauth2Client {
                clientRegistrationRepository = clientRegistrationRepository()
                authorizedClientRepository = authorizedClientRepository()
                authorizedClientService = authorizedClientService()
                authorizationCodeGrant {
                    authorizationRequestRepository = authorizationRequestRepository()
                    authorizationRequestResolver = authorizationRequestResolver()
                    accessTokenResponseClient = accessTokenResponseClient()
                }
            }
        }
        return http.build()
    }
}
----
======

除了 `HttpSecurity.oauth2Client()` DSL 外，还支持 XML 配置。

以下代码展示了 xref:servlet/appendix/namespace/http.adoc#nsa-oauth2-client[安全命名空间] 中提供的完整配置选项：

.OAuth2 客户端 XML 配置选项
[source,xml]
----
<http>
	<oauth2-client client-registration-repository-ref="clientRegistrationRepository"
				   authorized-client-repository-ref="authorizedClientRepository"
				   authorized-client-service-ref="authorizedClientService">
		<authorization-code-grant
				authorization-request-repository-ref="authorizationRequestRepository"
				authorization-request-resolver-ref="authorizationRequestResolver"
				access-token-response-client-ref="accessTokenResponseClient"/>
	</oauth2-client>
</http>
----

`OAuth2AuthorizedClientManager` 负责管理 OAuth 2.0 客户端的授权（或重新授权），并与一个或多个 `OAuth2AuthorizedClientProvider` 协同工作。

以下代码展示了一个如何注册 `OAuth2AuthorizedClientManager` `@Bean` 的示例，并将其与一个 `OAuth2AuthorizedClientProvider` 组合对象关联，该组合对象支持 `authorization_code`、`refresh_token`、`client_credentials` 和 `password` 授权许可类型：

[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Bean
public OAuth2AuthorizedClientManager authorizedClientManager(
		ClientRegistrationRepository clientRegistrationRepository,
		OAuth2AuthorizedClientRepository authorizedClientRepository) {

	OAuth2AuthorizedClientProvider authorizedClientProvider =
			OAuth2AuthorizedClientProviderBuilder.builder()
					.authorizationCode()
					.refreshToken()
					.clientCredentials()
					.password()
					.build();

	DefaultOAuth2AuthorizedClientManager authorizedClientManager =
			new DefaultOAuth2AuthorizedClientManager(
					clientRegistrationRepository, authorizedClientRepository);
	authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);

	return authorizedClientManager;
}
----

Kotlin::
+
[source,kotlin,role="secondary"]
----
@Bean
fun authorizedClientManager(
        clientRegistrationRepository: ClientRegistrationRepository,
        authorizedClientRepository: OAuth2AuthorizedClientRepository): OAuth2AuthorizedClientManager {
    val authorizedClientProvider: OAuth2AuthorizedClientProvider = OAuth2AuthorizedClientProviderBuilder.builder()
            .authorizationCode()
            .refreshToken()
            .clientCredentials()
            .password()
            .build()
    val authorizedClientManager = DefaultOAuth2AuthorizedClientManager(
            clientRegistrationRepository, authorizedClientRepository)
    authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider)
    return authorizedClientManager
}
----
======