[[httpheadersfilters]]
= HttpHeadersFilters

在将请求发送到下游服务（例如在 `NettyRoutingFilter` 中）之前，会应用 HttpHeadersFilters。

[[forwarded-headers-filter]]
== Forwarded 头部过滤器
`Forwarded` 头部过滤器用于创建一个 `Forwarded` 头部，并将其发送给下游服务。该过滤器会将当前请求的 `Host` 头、协议（scheme）和端口添加到已有的 `Forwarded` 头中。要启用此过滤器，请将 `spring.cloud.gateway.server.webmvc.trusted-proxies` 属性设置为一个 Java 正则表达式。该正则表达式定义了当代理出现在 `Forwarded` 头中时被信任的代理服务器。

[[removehopbyhop-headers-filter]]
== RemoveHopByHop 头部过滤器
`RemoveHopByHop` 头部过滤器会从转发的请求中移除指定的头部信息。默认移除的头部列表来自 https://tools.ietf.org/html/draft-ietf-httpbis-p1-messaging-14#section-7.1.3[IETF] 标准。

默认移除的头部包括：
*  Connection
*  Keep-Alive
*  Proxy-Authenticate
*  Proxy-Authorization
*  TE
*  Trailer
*  Transfer-Encoding
*  Upgrade

//如需更改此列表，请通过设置 `spring.cloud.gateway.filter.remove-hop-by-hop.headers` 属性来指定需要移除的头部名称列表。

[[xforwarded-headers-filter]]
== XForwarded 头部过滤器
`XForwarded` 头部过滤器用于创建多个 `X-Forwarded-*` 头部，并将其发送给下游服务。它使用当前请求的 `Host` 头、协议（scheme）、端口和路径来生成相应的头部。要启用此过滤器，请将 `spring.cloud.gateway.server.webmvc.trusted-proxies` 属性设置为一个 Java 正则表达式。该正则表达式定义了当代理出现在 `Forwarded` 头中时被信任的代理服务器。

各个 `X-Forwarded-*` 头部的生成可通过以下布尔属性进行控制（默认值为 true）：

- `spring.cloud.gateway.server.webmvc.x-forwarded.for-enabled`
- `spring.cloud.gateway.server.webmvc.x-forwarded.host-enabled`
- `spring.cloud.gateway.server.webmvc.x-forwarded.port-enabled`
- `spring.cloud.gateway.server.webmvc.x-forwarded.proto-enabled`
- `spring.cloud.gateway.server.webmvc.x-forwarded.prefix-enabled`

多个头部的追加行为可通过以下布尔属性进行控制（默认值为 true）：

- `spring.cloud.gateway.server.webmvc.x-forwarded.for-append`
- `spring.cloud.gateway.server.webmvc.x-forwarded.host-append`
- `spring.cloud.gateway.server.webmvc.x-forwarded.port-append`
- `spring.cloud.gateway.server.webmvc.x-forwarded.proto-append`
- `spring.cloud.gateway.server.webmvc.x-forwarded.prefix-append`