[[httpheadersfilters]]
= HttpHeadersFilters

`HttpHeadersFilters` 会在请求发送到下游服务之前对其进行处理，例如在 `NettyRoutingFilter` 中的应用。

[[forwarded-headers-filter]]
== Forwarded 头部过滤器
`Forwarded` 头部过滤器会创建一个 `Forwarded` 请求头并发送给下游服务。该过滤器会将当前请求的 `Host` 头、协议（scheme）和端口信息添加到已存在的 `Forwarded` 头中。要启用此过滤器，请将 `spring.cloud.gateway.server.webflux.trusted-proxies` 属性设置为一个 Java 正则表达式，该正则表达式用于定义当代理出现在 `Forwarded` 头中时哪些代理是可信的。

可以通过将以下属性设置为 `true`（默认为 `false`）来启用 `Forwarded by` 头部分：

- `spring.cloud.gateway.server.webflux.forwarded.by.enabled=true`

[[removehopbyhop-headers-filter]]
== RemoveHopByHop 头部过滤器
`RemoveHopByHop` 头部过滤器会从转发的请求中移除某些头部信息。默认移除的头部列表来自 IETF 规范 https://tools.ietf.org/html/draft-ietf-httpbis-p1-messaging-14#section-7.1.3。

.默认移除的头部包括：
*  Connection
*  Keep-Alive
*  Proxy-Authenticate
*  Proxy-Authorization
*  TE
*  Trailer
*  Transfer-Encoding
*  Upgrade

如需更改此列表，请通过设置 `spring.cloud.gateway.server.webflux.filter.remove-hop-by-hop.headers` 属性，指定需要移除的头部名称列表。

[[xforwarded-headers-filter]]
== XForwarded 头部过滤器
`XForwarded` 头部过滤器会生成多个 `X-Forwarded-*` 请求头并发送给下游服务。它使用当前请求的 `Host` 头、协议（scheme）、端口和路径来构建这些请求头。要激活此过滤器，请将 `spring.cloud.gateway.server.webflux.trusted-proxies` 属性设置为一个 Java 正则表达式，该正则表达式定义了在 `Forwarded` 头中被视为可信的代理。

各个 `X-Forwarded-*` 头的创建可通过以下布尔属性控制（默认值为 `true`）：

- `spring.cloud.gateway.server.webflux.x-forwarded.for-enabled`
- `spring.cloud.gateway.server.webflux.x-forwarded.host-enabled`
- `spring.cloud.gateway.server.webflux.x-forwarded.port-enabled`
- `spring.cloud.gateway.server.webflux.x-forwarded.proto-enabled`
- `spring.cloud.gateway.server.webflux.x-forwarded.prefix-enabled`

是否允许追加多个头字段可通过以下布尔属性控制（默认值为 `true`）：

- `spring.cloud.gateway.server.webflux.x-forwarded.for-append`
- `spring.cloud.gateway.server.webflux.x-forwarded.host-append`
- `spring.cloud.gateway.server.webflux.x-forwarded.port-append`
- `spring.cloud.gateway.server.webflux.x-forwarded.proto-append`
- `spring.cloud.gateway.server.webflux.x-forwarded.prefix-append`