[[native-image-method-security]]
= GraalVM 原生镜像中的方法安全

尽管 xref:servlet/authorization/method-security.adoc[方法安全] 在 GraalVM 原生镜像中是受支持的，但某些使用场景需要应用程序提供额外的提示（hints）。

== 使用 `@PreAuthorize` 和 `@PostAuthorize` 注解

当你自定义实现了 `UserDetails` 或 `Authentication` 类时，使用 `@PreAuthorize` 和 `@PostAuthorize` 注解就需要额外的提示。

假设你有一个如下的 `UserDetails` 自定义实现，并且该实现在你的 `UserDetailsService` 中被返回：

UserDetails 的自定义实现
[source,java]
----
public class CustomUserDetails implements UserDetails {

    private final String username;

    private final String password;

    private final Collection<? extends GrantedAuthority> authorities;

    public boolean isAdmin() {
        return this.authorities.contains(new SimpleGrantedAuthority("ROLE_ADMIN"));
    }

    // 构造函数、getter 和 setter 方法
}
----

然后你想在 `@PreAuthorize` 注解中使用 `isAdmin()` 方法，如下所示：

使用 isAdmin() 方法保护某个方法
[source,java]
----
@PreAuthorize("principal?.isAdmin()")
public String hello() {
    return "Hello!";
}
----

[NOTE]
====
请记住，你需要 xref:servlet/authorization/method-security.adoc#jc-enable-method-security[在配置类上添加 `@EnableMethodSecurity` 注解] 来启用方法安全注解。
====

如果你使用上述配置 https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html#native-image.developing-your-first-application[运行应用的原生镜像]，在调用 `hello()` 方法时会遇到类似以下的错误：

[source]
----
failed: java.lang.IllegalArgumentException: Failed to evaluate expression 'principal?.isAdmin()' with root cause
org.springframework.expression.spel.SpelEvaluationException: EL1004E: Method call: Method isAdmin() cannot be found on type com.mypackage.CustomUserDetails
----

这意味着 `CustomUserDetails` 类上找不到 `isAdmin()` 方法。  
原因是 Spring Security 使用反射来调用 `isAdmin()` 方法，而 GraalVM 原生镜像默认不支持反射。

要解决此问题，你需要向 GraalVM 原生镜像提供提示，允许对 `CustomUserDetails#isAdmin()` 方法进行反射调用。  
我们可以通过提供一个 https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html#native-image.advanced.custom-hints[自定义提示] 来实现这一点。  
本示例中，我们将使用 {spring-framework-reference-url}core.html#core.aot.hints.register-reflection-for-binding[`@RegisterReflectionForBinding` 注解]。

[NOTE]
====
你可能需要注册所有你想在 `@PreAuthorize` 和 `@PostAuthorize` 注解中使用的类。
====

使用 @RegisterReflectionForBinding
[source,java]
----
@Configuration
@RegisterReflectionForBinding(CustomUserDetails.class)
public class MyConfiguration {
    //...
}
----

就这样，现在你可以运行应用的原生镜像，功能将按预期正常工作。